spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 10500

logging:
  level:
    web: DEBUG