spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: microspringboot.infrastructure.jpa.CustomPhysicalNamingStrategy
  datasource:
    url: jdbc:postgresql://localhost:5432/product-service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
server:
  port: 10500
  error:
    include-stacktrace: never
