apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      name: inventory-service
      labels:
        app: inventory-service
    spec:
      containers:
        - name: inventory-service
          image: ngoduongkha/inventory-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  ports:
    - port: 80
      targetPort: 9191
  selector:
    app: inventory-service
