apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      name: order-service
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ngoduongkha/order-service:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
spec:
    ports:
        - port: 80
          targetPort: 9193
    selector:
        app: order-service
